/** Keyboard shortcuts in display form (`⇧⌘K`); locale strings take a placeholder, never these. */
export const keys = {
  "new-note": "⌘N",
  "open-folder": "⌘O",
  "git-sync": "⌘S",
  settings: "⌘,",
  undo: "⌘Z",
  redo: "⇧⌘Z",
  duplicate: "⌘D",
  "quick-open": "⌘K",
  commands: "⇧⌘K",
  search: "⌘F",
  prs: "⇧⌘P",
  calendar: "⇧⌘D",
  "select-all": "⌘A",
  copy: "⌘C",
  paste: "⌘V",
  "open-window": "⌘↩",
  escape: "Esc",
  "nav-deps": "←",
  "nav-dependents": "→",
  "nav-up": "↑",
  "nav-down": "↓",
  "nav-next": "⇥",
  "nav-prev": "⇧⇥",
  "edit-title": "↩",
  bold: "⌘B",
  italic: "⌘I",
  code: "⌘E",
  "code-alt": "⌘`",
  link: "⌘K",
  strike: "⇧⌘X",
  highlight: "⌘H",
} satisfies Record<string, string>;

export type KeyId = keyof typeof keys;
